### ISSUE TITLE
[TestNet] Transaction rejected by the server: TX decode failed

### ISSUE THREAD

**Issue by CharlesParent** [eveybcd/electrum#11]
Hello,

I just tried to make a transaction on the testnet network on the master branch, but there was an error after the transaction was signed when it is sent to the electrum server:
![image](https://user-images.githubusercontent.com/6388268/44660490-067b3c00-aa08-11e8-9527-c2dcf501b483.png)

If by any chance someone has an idea :) 

Thank you in advance for your time,

**Comment by Starry9** [comment]
Sorry, BCD electrum wallet does not support testnet for the time being.

**Comment by CharlesParent** [comment]
@Starry9 Ok thank you for your answer
