### ISSUE TITLE
BTC sent to unknown address while importing/sweeping keys

### ISSUE THREAD

**Issue by siddie** [eveybcd/electrum#3]
Hi guys. I tried to claim my BCD by importing private keys from bitcoin core wallet.  I used Electrum BCD 3.0.5 for Windows (Electrum-BCD-3.0.5.1-Windows-x86-64).

At first I tried it through Wallet->Private keys -> Import. The program crashed. After that I just created a new wallet through sweeping those keys.
All went well except for all the transactions I see are in "Not Verified" state.

After that I saw that my BTC balance went to 0 and I saw a transaction to the address I do not own. It is in the Bitcoin blochain. I know that sweeping creates new private keys and I own them. But seems that the transaction was made after sweeping. 

The transaction happened on 2018-01-15.

Can you help me in returning the BTC? 

PS: Yes, I know that I should have transferred the BTC to the new address just before claiming the fork, I just got tired and careless.

**Comment by starrygit** [comment]
Please upgrade Electrum BCD to 3.0.5.2 will fix it， Thanks
https://github.com/eveybcd/electrum/releases/tag/v3.0.5.2

**Comment by siddie** [comment]
Thanks. I have upgraded. This did not return my BTCs sent to unknown address while importing the private keys.

Can you tell me how that could have happened and how we can return the bitcoins?

**Comment by Starry9** [comment]
Did the transaction which you sent to unknown address has been confirmed? Please paste your transaction ID and address. @siddie

**Comment by siddie** [comment]
Please note, I have not sent anything.

After importing my BTC keys into the BCD wallet  (Electrum-BCD-3.0.5.1-Windows-x86-64) to claim the BCDs, I saw that the BTC from the BTC wallet had gone missing.

The transaction is:
https://blockchain.info/ru/address/12g3A33u412dzbZMVM6mDXbEgSkPoqUuju

**Comment by Starry9** [comment]
I know what your mean now. Your BTC send to a unknown address without your control when you importing private key to Electrum-BCD. 

But BCD has replay protection that a new present block hash filed in BCD new transaction and BCD tx_version is 12, BCD transaction is invalid when broadcast it in BTC network. 

Electrum-BCD only support create BCD transaction, when you importing private key in this wallet, you can create BCD new transaction, and can't broadcast it in BTC network.

Electrum-BCD 3.0.5.1 has a bug that transaction "Not Verified" when restore wallet which has transaction before BCD fork block height, and we fix it in new version.

If you BTC had gone missing, I can't help you return the BTC. Maybe there is some spyware in your computer, please check it.

I am so sorry that I can't help you.
