### ISSUE TITLE
Problem with 2FA wallets

### ISSUE THREAD

**Issue by danblack420** [eveybcd/electrum#4]
Error message: 'SimpleConfig' object is not iterable when trying to send from 2FA wallets am able to receive just fine but the error occurs everytime when trying to send.  

I am able to send and receive from standard wallets without issue however 2FA wallet consistently produces this error, tried to restore seed as 2FA wallet and remove the 2FA when restoring but no luck.  Also tried creating new wallet from seed as standard wallet with both the BIP-39 option selected and deselected however no effect. Did notice that it gets checksum failed message when trying to convert to 
BIP-39 standard wallet from 2FA.  So far error occurs on every combination I have tried on 2FA wallet. Tried selecting the import private keys option when creating wallet which causes program to completely crash and close right after it takes the key. Tried sweeping private key but get a P2H error without any detail. 

Maybe is having some problem communicating with trustedcoin as it doesn't want to bring up the verification portal? 

Please advise. Thanks in advance.

**Comment by mrbianchi** [comment]
Confirmed, I had the same issue, please fix it!

**Comment by mrbianchi** [comment]
I solved the problem, you can import it how a multsig
2FA are 2-3 multisig wallets
1. Import your 2FA wallet to electrum again disabling 2FA
2. Open the generated wallet .dat , go to down and copy the 2 xprv and the xpub (which doesn't have xprv)
3. Open electrum, restore a wallet multisig 2-3 , restore with the 2 xprv and the xpub
Ready, you can send the funds without getting error
Tip: 1FYnK8DU1KeMCbHC6nuy42TTBrPFtUkDHN 🥇

**Comment by danblack420** [comment]
I figured it out last night too took me 2 days of trying every possible configuration, am installing on Linux and mac now to test if problem exist on those versions as well or is limited to windows version.

**Comment by Starry9** [comment]
Trustedcoin which 2FA service provider does not support BitcoinDiamond， so we will disable 2FA in next version.

If you has a 2fa Electrum wallet, please resolve it by mrbianchi and danblack420 commented.

Thanks a lot @danblack420 @mrbianchi
