### ISSUE TITLE
Claim BCD from Trezor

### ISSUE THREAD

**Issue by ox1** [eveybcd/electrum#8]
Hello, what should I do in order to permit the login trough Trezor and claim my bitcoin diamond using this version of electrum?

Electrum already had a login through Trezor plugin but this repo is 318 commits behind the original repo, so any update to the trezor plugin interface is outdated. If I push the Trezor plugin updates to this repo, will we be able to claim my BCD linked to my BTC wallet on Trezor??
 
If it ain't possible, how can we claim bcd from trezor in a safe way, so without exposing our private keys/recovery seeds??

Thank you in advance

**Comment by Starry9** [comment]
Electrum BCD is not support Trezor now, and will be supoorted in the future
